/**
 * ## Language Icons & Branding (shared)
 *
 * Single source of truth for programming-language brand icons + colors.
 * Used by the languages listing page, language detail page, homepage
 * languages section, courses page, and kbar.
 *
 * Icons come from react-icons/si (Simple Icons). Fallbacks use the
 * language initial in a brand-colored chip.
 */

import React from 'react';
import {
  SiJavascript, SiPython, SiTypescript, SiOpenjdk, SiCplusplus,
  SiKotlin, SiSwift, SiRuby, SiPhp, SiSharp, SiGo, SiRust,
  SiScala, SiR, SiDart, SiElixir, SiHaskell, SiLua, SiGnubash,
  SiC, SiJulia, SiPerl, SiFortran, SiApachegroovy, SiClojure, SiErlang, SiAssemblyscript,
  SiOcaml, SiFsharp, SiCrystal, SiNim, SiZig, SiV, SiD, SiRacket,
  SiElm, SiGraphql, SiGleam, SiSolidity, SiWebassembly, SiAda, SiHaxe, SiTerraform, SiMarkdown,
  SiLatex, SiCommonlisp, SiProcessingfoundation, SiScratch, SiWolframlanguage, SiGodotengine, SiLabview, SiAutohotkey, SiJson, SiToml,
  SiPurescript, SiSass, SiLess, SiPug, SiJinja, SiNixos, SiDocker, SiKubernetes, SiAnsible, SiLlvm,
  SiReact, SiVuedotjs, SiAngular, SiSvelte, SiNodedotjs, SiExpress, SiFlutter, SiLinux, SiPostgresql, SiRedis,
  SiSpring, SiDjango, SiLaravel, SiNextdotjs, SiTailwindcss, SiBootstrap, SiNginx, SiMongodb, SiElasticsearch, SiMysql,
  SiGrafana, SiPrometheus, SiApachekafka, SiRabbitmq, SiApacheairflow, SiSqlite, SiJenkins, SiGitlab, SiGithubactions, SiNeovim,
  SiAstro,
  SiBun, SiDeno, SiNestjs, SiRemix, SiFastify, SiHono, SiSelenium, SiCypress, SiVitest, SiJest,
  SiVite, SiPrisma, SiSocketdotio, SiThreedotjs, SiChartdotjs, SiEslint, SiPrettier, SiWebpack, SiElectron, SiExpo,
  SiPandas, SiScikitlearn, SiPytorch, SiOpencv, SiHuggingface, SiLangchain,
  SiTensorflow, SiMlflow, SiOllama, SiCrewai, SiAnthropic,
} from 'react-icons/si';
// lucide-react is used only for the AI Safety domain — simple-icons has no
// fitting safety/shield icon, so this single exception lives here.
import { Shield } from 'lucide-react';

/** Icon node builder keyed by slug. Falls back to the language initial. */
export function getLangIcon(slug: string, size = 22): React.ReactNode {
  const icons: Record<string, React.ReactNode> = {
    javascript: <SiJavascript size={size} />,
    python: <SiPython size={size} />,
    typescript: <SiTypescript size={size} />,
    java: <SiOpenjdk size={size} />,
    cpp: <SiCplusplus size={size} />,
    kotlin: <SiKotlin size={size} />,
    swift: <SiSwift size={size} />,
    ruby: <SiRuby size={size} />,
    php: <SiPhp size={size} />,
    csharp: <SiSharp size={size} />,
    go: <SiGo size={size} />,
    rust: <SiRust size={size} />,
    scala: <SiScala size={size} />,
    r: <SiR size={size} />,
    dart: <SiDart size={size} />,
    elixir: <SiElixir size={size} />,
    haskell: <SiHaskell size={size} />,
    lua: <SiLua size={size} />,
    shell: <SiGnubash size={size} />,
    c: <SiC size={size} />,
    matlab: <span className="text-[11px] font-bold">M</span>,
    julia: <SiJulia size={size} />,
    perl: <SiPerl size={size} />,
    fortran: <SiFortran size={size} />,
    groovy: <SiApachegroovy size={size} />,
    clojure: <SiClojure size={size} />,
    erlang: <SiErlang size={size} />,
    assembly: <SiAssemblyscript size={size} />,
    cobol: <span className="text-[11px] font-bold">C</span>,
    ocaml: <SiOcaml size={size} />,
    fsharp: <SiFsharp size={size} />,
    crystal: <SiCrystal size={size} />,
    nim: <SiNim size={size} />,
    zig: <SiZig size={size} />,
    v: <SiV size={size} />,
    d: <SiD size={size} />,
    racket: <SiRacket size={size} />,
    scheme: <span className="text-[11px] font-bold">λ</span>,
    prolog: <span className="text-[11px] font-bold">?</span>,
    sql: <span className="text-[11px] font-bold">S</span>,
    elm: <SiElm size={size} />,
    graphql: <SiGraphql size={size} />,
    gleam: <SiGleam size={size} />,
    solidity: <SiSolidity size={size} />,
    webassembly: <SiWebassembly size={size} />,
    ada: <SiAda size={size} />,
    haxe: <SiHaxe size={size} />,
    terraform: <SiTerraform size={size} />,
    markdown: <SiMarkdown size={size} />,
    latex: <SiLatex size={size} />,
    'common-lisp': <SiCommonlisp size={size} />,
    processing: <SiProcessingfoundation size={size} />,
    scratch: <SiScratch size={size} />,
    'wolfram-language': <SiWolframlanguage size={size} />,
    gdscript: <SiGodotengine size={size} />,
    labview: <SiLabview size={size} />,
    autohotkey: <SiAutohotkey size={size} />,
    json: <SiJson size={size} />,
    toml: <SiToml size={size} />,
    purescript: <SiPurescript size={size} />,
    sass: <SiSass size={size} />,
    less: <SiLess size={size} />,
    pug: <SiPug size={size} />,
    jinja: <SiJinja size={size} />,
    nix: <SiNixos size={size} />,
    docker: <SiDocker size={size} />,
    kubernetes: <SiKubernetes size={size} />,
    ansible: <SiAnsible size={size} />,
    llvm: <SiLlvm size={size} />,
    react: <SiReact size={size} />,
    vue: <SiVuedotjs size={size} />,
    angular: <SiAngular size={size} />,
    svelte: <SiSvelte size={size} />,
    nodejs: <SiNodedotjs size={size} />,
    express: <SiExpress size={size} />,
    flutter: <SiFlutter size={size} />,
    linux: <SiLinux size={size} />,
    postgresql: <SiPostgresql size={size} />,
    redis: <SiRedis size={size} />,
    spring: <SiSpring size={size} />,
    django: <SiDjango size={size} />,
    laravel: <SiLaravel size={size} />,
    nextjs: <SiNextdotjs size={size} />,
    tailwind: <SiTailwindcss size={size} />,
    bootstrap: <SiBootstrap size={size} />,
    nginx: <SiNginx size={size} />,
    mongodb: <SiMongodb size={size} />,
    elasticsearch: <SiElasticsearch size={size} />,
    mysql: <SiMysql size={size} />,
    grafana: <SiGrafana size={size} />,
    prometheus: <SiPrometheus size={size} />,
    kafka: <SiApachekafka size={size} />,
    rabbitmq: <SiRabbitmq size={size} />,
    airflow: <SiApacheairflow size={size} />,
    sqlite: <SiSqlite size={size} />,
    jenkins: <SiJenkins size={size} />,
    gitlab: <SiGitlab size={size} />,
    'github-actions': <SiGithubactions size={size} />,
    neovim: <SiNeovim size={size} />,
    astro: <SiAstro size={size} />,
    bun: <SiBun size={size} />,
    deno: <SiDeno size={size} />,
    nestjs: <SiNestjs size={size} />,
    remix: <SiRemix size={size} />,
    fastify: <SiFastify size={size} />,
    hono: <SiHono size={size} />,
    selenium: <SiSelenium size={size} />,
    cypress: <SiCypress size={size} />,
    vitest: <SiVitest size={size} />,
    jest: <SiJest size={size} />,
    vite: <SiVite size={size} />,
    prisma: <SiPrisma size={size} />,
    socketio: <SiSocketdotio size={size} />,
    threejs: <SiThreedotjs size={size} />,
    chartjs: <SiChartdotjs size={size} />,
    eslint: <SiEslint size={size} />,
    prettier: <SiPrettier size={size} />,
    webpack: <SiWebpack size={size} />,
    electron: <SiElectron size={size} />,
    expo: <SiExpo size={size} />,
    'data-science': <SiPandas size={size} />,
    'machine-learning': <SiScikitlearn size={size} />,
    'deep-learning': <SiPytorch size={size} />,
    'computer-vision': <SiOpencv size={size} />,
    nlp: <SiHuggingface size={size} />,
    'generative-ai': <SiLangchain size={size} />,
    'reinforcement-learning': <SiTensorflow size={size} />,
    mlops: <SiMlflow size={size} />,
    'llm-engineering': <SiOllama size={size} />,
    'ai-agents': <SiCrewai size={size} />,
    'prompt-engineering': <SiAnthropic size={size} />,
    'ai-safety': <Shield size={size} strokeWidth={2.2} />,
  };
  return icons[slug] || null;
}

/** Brand background classes keyed by slug (used for icon chips). */
export function getLangBg(slug: string): string {
  const bg: Record<string, string> = {
    javascript: 'bg-[#F7DF1E] text-black',
    python: 'bg-[#3776AB] text-white',
    typescript: 'bg-[#3178C6] text-white',
    java: 'bg-[#ED8B00] text-white',
    cpp: 'bg-[#00599C] text-white',
    kotlin: 'bg-[#7F52FF] text-white',
    swift: 'bg-[#F05138] text-white',
    ruby: 'bg-[#CC342D] text-white',
    php: 'bg-[#777BB4] text-white',
    csharp: 'bg-[#239120] text-white',
    go: 'bg-[#00ADD8] text-white',
    rust: 'bg-[#000000] text-white',
    scala: 'bg-[#DC322F] text-white',
    r: 'bg-[#276DC3] text-white',
    dart: 'bg-[#0175C2] text-white',
    elixir: 'bg-[#4B275F] text-white',
    haskell: 'bg-[#5D4F85] text-white',
    lua: 'bg-[#000080] text-white',
    shell: 'bg-[#4EAA25] text-white',
    c: 'bg-[#A8B9CC] text-black',
    matlab: 'bg-[#E16737] text-white',
    julia: 'bg-[#4063D8] text-white',
    perl: 'bg-[#39457E] text-white',
    fortran: 'bg-[#734F96] text-white',
    groovy: 'bg-[#4298B8] text-white',
    clojure: 'bg-[#5881D8] text-white',
    erlang: 'bg-[#A90533] text-white',
    assembly: 'bg-[#6E4C13] text-white',
    cobol: 'bg-[#005C99] text-white',
    ocaml: 'bg-[#EC6813] text-white',
    fsharp: 'bg-[#378BBA] text-white',
    crystal: 'bg-[#000000] text-white',
    nim: 'bg-[#FFE953] text-black',
    zig: 'bg-[#F7A41D] text-black',
    v: 'bg-[#5D87BF] text-white',
    d: 'bg-[#BA595E] text-white',
    racket: 'bg-[#9F1D20] text-white',
    scheme: 'bg-[#1B1B1B] text-white',
    prolog: 'bg-[#E61C24] text-white',
    sql: 'bg-[#336791] text-white',
    elm: 'bg-[#60B5CC] text-white',
    graphql: 'bg-[#E535AB] text-white',
    gleam: 'bg-[#FFC97B] text-black',
    solidity: 'bg-[#363636] text-white',
    webassembly: 'bg-[#654FF0] text-white',
    ada: 'bg-[#01A4FF] text-white',
    haxe: 'bg-[#F5871F] text-white',
    terraform: 'bg-[#7B42BC] text-white',
    markdown: 'bg-[#000000] text-white',
    latex: 'bg-[#008080] text-white',
    'common-lisp': 'bg-[#FF6600] text-white',
    processing: 'bg-[#0096D6] text-white',
    scratch: 'bg-[#F7A41D] text-black',
    'wolfram-language': 'bg-[#DD1100] text-white',
    gdscript: 'bg-[#478CBF] text-white',
    labview: 'bg-[#DDE020] text-black',
    autohotkey: 'bg-[#334455] text-white',
    json: 'bg-[#000000] text-white',
    toml: 'bg-[#9C4221] text-white',
    purescript: 'bg-[#333333] text-white',
    sass: 'bg-[#CC6699] text-white',
    less: 'bg-[#1D365D] text-white',
    pug: 'bg-[#A86454] text-white',
    jinja: 'bg-[#B41717] text-white',
    nix: 'bg-[#5277C3] text-white',
    docker: 'bg-[#2496ED] text-white',
    kubernetes: 'bg-[#326CE5] text-white',
    ansible: 'bg-[#EE0000] text-white',
    llvm: 'bg-[#4E8CAB] text-white',
    react: 'bg-[#61DAFB] text-black',
    vue: 'bg-[#4FC08D] text-white',
    angular: 'bg-[#DD0031] text-white',
    svelte: 'bg-[#FF3E00] text-white',
    nodejs: 'bg-[#339933] text-white',
    express: 'bg-[#000000] text-white',
    flutter: 'bg-[#02569B] text-white',
    linux: 'bg-[#FCC624] text-black',
    postgresql: 'bg-[#4169E1] text-white',
    redis: 'bg-[#DC382D] text-white',
    spring: 'bg-[#6DB33F] text-white',
    django: 'bg-[#092E20] text-white',
    laravel: 'bg-[#FF2D20] text-white',
    nextjs: 'bg-[#000000] text-white',
    tailwind: 'bg-[#06B6D4] text-white',
    bootstrap: 'bg-[#7952B3] text-white',
    nginx: 'bg-[#009639] text-white',
    mongodb: 'bg-[#47A248] text-white',
    elasticsearch: 'bg-[#005571] text-white',
    mysql: 'bg-[#4479A1] text-white',
    grafana: 'bg-[#F46800] text-white',
    prometheus: 'bg-[#E6522C] text-white',
    kafka: 'bg-[#231F20] text-white',
    rabbitmq: 'bg-[#FF6600] text-white',
    airflow: 'bg-[#017CEE] text-white',
    sqlite: 'bg-[#003B57] text-white',
    jenkins: 'bg-[#D24939] text-white',
    gitlab: 'bg-[#FC6D26] text-white',
    'github-actions': 'bg-[#2088FF] text-white',
    neovim: 'bg-[#57A143] text-white',
    astro: 'bg-[#BC52EE] text-white',
    bun: 'bg-[#14151A] text-white',
    deno: 'bg-[#000000] text-white',
    nestjs: 'bg-[#E0234E] text-white',
    remix: 'bg-[#121212] text-white',
    fastify: 'bg-[#202020] text-white',
    hono: 'bg-[#E36002] text-white',
    selenium: 'bg-[#43B02A] text-white',
    cypress: 'bg-[#17202C] text-white',
    vitest: 'bg-[#6E9F18] text-white',
    jest: 'bg-[#C21325] text-white',
    vite: 'bg-[#646CFF] text-white',
    prisma: 'bg-[#2D3748] text-white',
    socketio: 'bg-[#010101] text-white',
    threejs: 'bg-[#000000] text-white',
    chartjs: 'bg-[#FF6384] text-white',
    eslint: 'bg-[#4B32C3] text-white',
    prettier: 'bg-[#F7B93E] text-black',
    webpack: 'bg-[#8DD6F9] text-black',
    electron: 'bg-[#47848F] text-white',
    expo: 'bg-[#000020] text-white',
    'data-science': 'bg-[#150458] text-white',
    'machine-learning': 'bg-[#F7931E] text-black',
    'deep-learning': 'bg-[#EE4C2C] text-white',
    'computer-vision': 'bg-[#5C3EE8] text-white',
    nlp: 'bg-[#1C3C3C] text-[#FFD21E]',
    'generative-ai': 'bg-[#1C3C3C] text-[#38E8B8]',
    'reinforcement-learning': 'bg-[#FF6F00] text-white',
    mlops: 'bg-[#0194E2] text-white',
    'llm-engineering': 'bg-[#000000] text-[#38E8B8]',
    'ai-agents': 'bg-[#7C3AED] text-white',
    'prompt-engineering': 'bg-[#D97757] text-white',
    'ai-safety': 'bg-[#0EA5E9] text-white',
  };
  return bg[slug] || 'bg-accent text-white';
}

/** Hero banner background + icon chip colors (language detail page). */
export function getLangHero(slug: string): { bg: string; iconBg: string } {
  const chip = getLangBg(slug);
  const bgColor = chip.split(' ')[0] || 'bg-accent';
  return { bg: bgColor, iconBg: chip };
}
