/**
 * Feed source definition — a single engineering blog we track.
 * Only stores metadata/links, never the actual content.
 */
export interface FeedSource {
  id: string;
  name: string;
  rssUrl: string;
  siteUrl: string;
  icon?: string;
  tags: string[];
  description: string;
  addedBy: 'curator' | 'community';
  language: string;
}

/**
 * A single article from the registry cache.
 * This is the raw format stored in the registry JSON files.
 */
export interface RegistryFeedItem {
  guid: string;
  title: string;
  link: string;
  summary: string | null;
  author: string | null;
  publishedAt: string | null;
}

/**
 * A feed's data as stored in the registry JSON file.
 */
export interface RegistryFeedData {
  feedId: string;
  feedName: string;
  feedSiteUrl: string;
  feedRssUrl: string;
  tags: string[];
  updatedAt: string;
  items: RegistryFeedItem[];
  totalIndexed: number;
}

/**
 * The combined cache file generated by fetch-feed-cache.mjs.
 * Contains ALL articles from ALL feeds, indexed by feed ID.
 */
export interface FeedCache {
  version: number;
  updatedAt: string;
  feedCount: number;
  totalItems: number;
  feeds: Record<string, RegistryFeedData>;
}

/**
 * Daily delta file generated by the registry's update-feeds.ts.
 * Contains ONLY the items added in the most recent run.
 * The website's ISR fetches this tiny file and merges it into the local cache,
 * avoiding the need to re-download all 51 feed JSON files.
 */
export interface DeltaCache {
  /** YYYY-MM-DD date of this delta */
  date: string;
  /** ISO timestamp when this delta was generated */
  generatedAt: string;
  /** New items by feed ID — only feeds that had new content */
  items: Record<string, RegistryFeedItem[]>;
  /** Total new items across all feeds */
  totalNewItems: number;
  /** Number of feeds that had new items */
  feedCount: number;
}

/**
 * A single article after being enriched with feed metadata
 * (tags, feed name, site URL) for display.
 */
export interface Article {
  id: string;
  feedId: string;
  feedName: string;
  feedSiteUrl: string;
  title: string;
  url: string;
  author: string | null;
  summary: string | null;
  contentSnippet: string | null;
  publishedAt: string | null;
  tags: string[];
  /** HN-style upvotes (0 initially) */
  upvotes: number;
}

/**
 * Response from the /api/feed endpoint.
 */
export interface FeedApiResponse {
  articles: Article[];
  feeds: string[];
  /** Total articles in this response */
  total: number;
  /** Cursor for pagination — pass as ?cursor= to get the next batch */
  cursor: string | null;
  errors: Array<{ feedId: string; error: string }>;
}

/**
 * User's feed preferences stored in localStorage.
 */
export interface UserFeedPreferences {
  selectedFeeds: string[];
  selectedTags: string[];
  hiddenFeeds: string[];
  sortBy: 'newest' | 'hn-rank';
}

/**
 * A bookmarked article stored in localStorage.
 * Only stores metadata + link, never the actual content.
 */
export interface BookmarkEntry {
  url: string;
  title: string;
  feedName: string;
  feedId: string;
  savedAt: string;
}
